id: I37B9913B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T02:32:19+00:00'
last_modified: '2022-06-09T04:41:55.413639+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20468
  title: བྱང་ཐང་སྨུག་པ་ཁེར་རྒྱུག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    CBAB:
      image_group_id: I8LS20470
      title: Volume 1 of byang sgra snyan gyi rtsom btus [-] byang thang smug pa kher
        rgyug
      total_pages: 212
      order: 1
      base_file: CBAB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
