id: P008128
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20468
  title: བྱང་ཐང་སྨུག་པ་ཁེར་རྒྱུག
  author: ''
  volumes:
    464f1926bfaf42a5844b80e80edc93dd:
      image_group_id: I8LS20470
      title: ''
      volume_number: 1
      total_pages: 212
ebook_metadata:
  title: བྱང་ཐང་སྨུག་པ་ཁེར་རྒྱུག
  author: ''
  sku: P008128
  cover: cover.jpg
  layers:
  - pagination
